# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               theirixblog
tagline:             'A Few Thoughts About Development'
description:         ''
url:                 http://theirix.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Eugene Seliverstov
  url:               https://omniverse.ru/theirix
  email:             theirix@gmail.com

# Custom vars
version:             1.0.0
